.TH agrego-manage-@@ENDPOINT@@ "8" "July 2010" "Agrego daemon" "agrego-manage-@@ENDPOINT@@"
.SH NAME
agrego-manage-@@ENDPOINT@@ \- Launch the Agrego @@ENDPOINT@@ daemon
.SH SYNOPSIS
.B agrego-manage-@@ENDPOINT@@
.RB [\| \-f \||\| \-\-force \|]
.RB [\| \-q \||\| \-\-quiet \|]
.RB (\| list \||\| delall \|)
.br
.B agrego-manage-@@ENDPOINT@@
.RB [\| \-f \||\| \-\-force \|]
.RB [\| \-q \||\| \-\-quiet \|]
.RB (\| add \||\| del \|)
.IR agrego_instance_name
.SH DESCRIPTION
.\" Add any additional description here
.PP
Manage Agrego @@ENDPOINT@@ instance.
An Agrego @@ENDPOINT@@ instance is composed by (replace AGREGOINSTANCE by the real Agrego instance name):
/etc/agrego-@@ENDPOINT@@/AGREGOINSTANCE/
/etc/init.d/agrego-@@ENDPOINT@@-AGREGOINSTANCE
.TP
\fB\-f\fR, \fB\-\-force\fR
Don't ask question just do it. This parameter is useless with the action \fBlist\fR.
.TP
\fB\-q\fR, \fB\-\-quiet\fR
Don't say any word except for question.
.SH ACTION
.TP
\fBlist\fR
will list all installed Agrego instance.
.TP
\fBadd\fR \fIagrego_instance_name\fR
will add a new Agrego instance, so it will create the directory
/etc/agrego-@@ENDPOINT@@/agrego_instance_name/ and fill it with 3 files
(start.sh, stop.sh and agrego.ini). And also create the daemon script,
/etc/init.d/agrego-@@ENDPOINT@@-agrego_instance_name. All this files come from
/usr/share/agrego-@@ENDPOINT@@/.
.br
After the script will ask you if you want to
launch the daemon at boot. If \fB-f\fR is specified this question is not asked
and the daemon will be launched at next reboot.
.TP
\fBdel\fR \fIagrego_instance_name\fR
will del an existing Agrego instance, it will remove what has been created with the \fBadd\fR action.
.TP
\fBdelall\fR
will run a del for all existing Agrego instance.
.SH AUTHOR
Written by the Agrego Team <team@agrego.net>
.SH "REPORTING BUGS"
Please report bugs to <bug@agrego.net>
.br
Agrego project home page: <http://agrego.net/>
.SH COPYRIGHT
Copyright \(co 2010 The Agrego Team <team@agrego.net>.
License BSD
.br
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.
.SH "SEE ALSO"
.BR agrego-@@ENDPOINT@@(8)
